### ISSUE TITLE
Uncorect manual on forge.puppet.com

### ISSUE THREAD

**Issue by belskiiartem** [sorrowless/puppet-twemproxy#3]
On https://forge.puppet.com/sbog/twemproxy
you write
mod 'sbog-twemproxy', '0.1.1'
but when I use it I have error
[R10K::Action::Deploy::Environment - ERROR] Module sbog-twemproxy with args "0.1.1" doesn't have an implementation. (Are you using the right arguments?)

When I use 
mod 'sbog/twemproxy', '0.1.1'
all ok, so please fit this.

Thanks!

**Comment by sorrowless** [comment]
Hi Artem,
unfortunately, this line is autogenerated by Puppet Forge itself and I don't know a way to fix it at my side.
